### ISSUE TITLE
Errors while adding package

### ISSUE THREAD

**Issue by rogolius** [metstrike/meteor-oracle#1]
Hi,

When I try to add the package into my project, I receive the following error:
"While checking for metstrike:meteor-oracle@0.1.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform."

Meteor version: 1.2.1
O.S.: CentOS Linux release 7.1.1503 (Core)

Thank you,
Catalin

**Comment by metstrike** [comment]
Thank you for trying this package! It has a binary npm dependency (node-oracledb) so I had to explicitly publish it for os.linux.x86_64 architecture. **Please try to add metstrike:meteor-oracle to your project again.**
