### ISSUE TITLE
does it work on mac?

### ISSUE THREAD

**Issue by asosahn** [metstrike/meteor-oracle#11]
While checking for metstrike:meteor-oracle@0.2.0:
error: No compatible binary build found for this package. Contact the package
author and ask them to publish it for your platform.
I have installed the oracledb package and works fine on nodejs.

**Comment by metstrike** [comment]
Yes it should work on mac, even though the binaries have been compiled and published to the atmospherejs for **os.linux.x86_64** architecture only.

For **OSX** I would suggest to check out this repository, set environment variable to point meteor to it and then the binaries should be automatically recompiled for your local platform. Please try the following steps:

```
$ cd ~/workspace
$ git clone https://github.com/metstrike/meteor-oracle.git
$ export PACKAGE_DIRS="~/workspace"

$ cd ~/workspace/todos-oracle
$ meteor add metstrike:meteor-oracle
```
