### ISSUE TITLE
ORA-00904 "Status" invalid identifier error

### ISSUE THREAD

**Issue by camilomv17** [metstrike/meteor-oracle#13]
Hi, 

I'm trying to connect to an oracle instance, but I'm getting this weird error:

ERROR in SQL:  select table_name as "tableName", status, num_rows as "numRows" from user_tables where table_name = :1
ORA-00904: "STATUS": invalid identifier

I'm running in Ubuntu 14.04, downloaded instant client as instructed, using LD_LIBRARY_PATH variable. 

Please help.
Thanks a lot.

**Comment by metstrike** [comment]
Thank you for reporting this issue. Do you know what version of Oracle you are connecting to? It looks like in that version the user_tables doesn't have the STATUS column.

**Comment by camilomv17** [comment]
Hi, 
thanks for your quick response. 
I don't know the version (I have restricted access, its a customer db), but I've just check directly through a Query and you're right, Theres no STATUS column. 

As you may know, I can't change the db version, because its used for other apps. 

what can I do in this case?

Thanks!

**Comment by metstrike** [comment]
The version of your database should be printed out when you run sqlplus, e.g.

```
$ sqlplus 

SQL*Plus: Release 11.2.0.2.0 Production on Sun May 1 18:08:53 2016

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

Enter user-name:
Enter password: 

Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL> 
```

The driver was tested on Oracle 11g and Oracle 12c, even though the dependency on the STATUS column could be removed, there might be other issues when using older version of Oracle.

I would recommend to evaluate the driver on Oracle 11g XE, which can be downloaded from Oracle website for free.

**Comment by camilomv17** [comment]
Ok So I was able to make this work. 
I created a modified local package and change "status" for TABLE_LOCK in oracle_db.js, function RefreshTable. After that it worked. 
I hope this status field doesn't affect the routines. 

Thanks for your help!

**Comment by metstrike** [comment]
Thank you for your comment, we will remove the dependency on STATUS column in our next release.
