### ISSUE TITLE
Can't add package for meteor version 1.3.2.4

### ISSUE THREAD

**Issue by chujitsunaneko** [metstrike/meteor-oracle#14]
Hye, i had problem to add the package on my platform..

Any help?

I got error as below,
![image](https://cloud.githubusercontent.com/assets/16010353/15353393/6871e3ae-1d1b-11e6-8838-81ea8a4a167c.png)

I have tried your solution proposed,
$ cd ~/workspace
$ git clone https://github.com/metstrike/meteor-oracle.git
$ export PACKAGE_DIRS="~/workspace"

$ cd ~/workspace/todos-oracle
$ meteor add metstrike:meteor-oracle

but it doesnt worked.
TQ.

**Comment by metstrike** [comment]
Hello, were you able to resolve this issue? Based on the screenshot I assume you tried to install the package on windows, but we haven't yet built and published to Atmosphere the package for windows platform.

**Comment by chujitsunaneko** [comment]
Hi, 
Sorry I didn't notice that you haven't yet publish it for Windows.. Thank you for replying.. But I can't resolve the issue, so I try to use the npm.

I hope you'll be able to publish it for Windows soon.. :'D
Because i really had difficulties to install and setup the oracle driver in Windows for my meteor project.
