### ISSUE TITLE
libc.so.6: version 'GLIBC_2.14' not found

### ISSUE THREAD

**Issue by marczzio** [metstrike/meteor-oracle#15]
Hi, im trying to run the meteor apps with metstrike:meteor-oracle, and it said GLIBC_2.14 not found. 
I already checked the libc.so.6. It is exists, but with the version 2.12. 
Do you know how to solve it??
- fyi im using ORACLE LINUX 6 

thank you

**Comment by metstrike** [comment]
Hello, the published version of the package was build with libc 2.14. Is there a way to update your version of c libraries to 2.14?

Another solution would be to check out the git repository and build the package yourself. Can you try the following steps:

$ cd ~/workspace 
$ git clone https://github.com/metstrike/meteor-oracle.git 
$ export PACKAGE_DIRS="~/workspace" 
$ cd ~/workspace/todos-oracle 
$ meteor add metstrike:meteor-oracle

**Comment by marczzio** [comment]
I tried to install the glibc 2.14 in other directory (/opt/glibc-2.14/) according to this [reference](http://unix.stackexchange.com/questions/176489/how-to-update-glibc-to-2-14-in-centos-6-5) and this [reference](http://imperx.com/wp-content/uploads/Member/Cameras/Bobcat_Gen2/GEV%20Linux/Workaround_to_install_GLIBC_2.14_to_CentOS_6.7.pdf).

I should set LD_LIBRARY_PATH with two values, 
1. `export LD_LIBRARY_PATH=/opt/glibv-2.14/lib/  ==> to set glibc2.14`
2. `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/instanclient_11_2/`

but when I tried to run meteor, I still got an error, LOL

```
Unexpected mongo exit code 1. Restarting.     
Unexpected mongo exit code 1. Restarting.     
Unexpected mongo exit code 1. Restarting.     
Can't start Mongo server.                     
MongoDB failed global initialization

Looks like MongoDB doesn't understand your locale settings.
```

when I tried to run `locale` command, the result is

```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

is it me wrong with the environment variable??

**Comment by metstrike** [comment]
The mongo is probably crashing because of glibc2.14.

Could you go back to 2.12 and try the other solution I suggested, checking out the source code of the meteor-oracle package? I provided the steps in my previous answer.

**Comment by marczzio** [comment]
so, I must create the meteor project inside the workspace which is the repository that I clone?? 
And do have set LD_LIBRARY_PATH again??

**Comment by marczzio** [comment]
Hi, Finally I solved those problems above by changing the VM from Oracle Linux to Ubuntu 4.12. It is smooth and work fine. 

But I want to ask 2 questions.
1. when I tried to create new collection => `var col1 = new Oracle.Collection("MTL_PARAMETERS")`, it failed. The error log said that `name already used by an existing object`. is there a way to select data from existing table in oracle, instead of creating new one?? It seems the command `new Oracle.Collection` create the new table.
2. When I tried to create new collection => `var col1 = new Oracle.Collection("todos")` which todos is not yet exists in oracle schema, it worked. When I describe in TOAD for oracle, the table "todos" exists. But when I tried to select data in TOAD it said the table does not exists. and then I also try to find data in sqlplus, the table does not exists.

thank you.

**Comment by metstrike** [comment]
> so, I must create the meteor project inside the workspace which is the repository that I clone?? 
> And do have set LD_LIBRARY_PATH again??

You can clone the todos meteor project from another github repository. Yes the LD_LIBRARY_PATH must be properly set. So more accurate sequence of steps I tried to suggest would be:

$ cd ~/workspace
$ git clone https://github.com/metstrike/meteor-oracle.git
$ git clone https://github.com/metstrike/todos-oracle.git
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/instanclient_11_2/
$ export PACKAGE_DIRS="~/workspace"
$ cd ~/workspace/todos-oracle
$ meteor add metstrike:meteor-oracle

**Comment by metstrike** [comment]
> But I want to ask 2 questions.
> 
> when I tried to create new collection => var col1 = new Oracle.Collection("MTL_PARAMETERS"), it failed. The error log said that name already used by an existing object. is there a way to select data from existing table in oracle, instead of creating new one?? It seems the command new Oracle.Collection create the new table.

Is MTL_PARAMETERS actually a table in the schema you are connecting to? If it's a view, or synonym, or owned by another schema it will not work in this version. We are planning to support views in the next release of this package. Please run the sql below to see what type of object it actually is and who is the owner:

`select * from all_objects where object_name = 'MTL_PARAMETERS'` 

> When I tried to create new collection => var col1 = new Oracle.Collection("todos") which todos is not yet exists in oracle schema, it worked. When I describe in TOAD for oracle, the table "todos" exists. But when I tried to select data in TOAD it said the table does not exists. and then I also try to find data in sqlplus, the table does not exists.

The table names created by this package are case sensitive. Did you put the name of the table in quotes? You can try in sql*plus or toad:

`select * from "todos";`

**Comment by marczzio** [comment]
Yeah you're right! The `MTL_PARAMETERS` are in multiple owners, only in INV Schema, MTL_PARAMETERS is table, other than that, is synonym. So in Meteor is should code like this `var col1 = new Oracle.Collection("INV.MTL_PARAMETERS");`. 
For `"todos"` table I should type the query in TOAD like your answer, and it is exists. Great!

But when I tried to read data from Meteor, like `var rows = col1.find({}).fetch();`, it return the empty array `[]`. It seems the meteor cannot read the data inside both `INV.MTL_PARAMETERS` and `"todos"`. I already tried to loop the data, and the result is the same.

**Comment by metstrike** [comment]
> So in Meteor is should code like this var col1 = new Oracle.Collection("INV.MTL_PARAMETERS");. 

Unfortunately, accessing tables in other schemas is not implemented in this version. Only access to plain tables in current schema is currently working, access through views, synonyms, materialized views is not implemented. We plan to add support for views in next release.

> But when I tried to read data from Meteor, like var rows = col1.find({}).fetch();, it return the empty array []

Did you try the find() on the client or the server side? If you have any data in the "todos" table, the find/fetch should definitely retrieve them on the server side. On the client side (in the browser's console) you may need to subscribe to the data collection first.

**Comment by marczzio** [comment]
`Did you try the find() on the client or the server side?`
In `lib` folder along with connection string, im sorry this is my bad.

`Only access to plain tables in current schema is currently working` 
this is my connection string.

```
Oracle.setDefaultOracleOptions(
    {connection:
        {user: "APPS", 
        password: "APPS", 
        connectString : "xxx.xxx.xxx.xxx:1532/SID"
        }
});
```

so the currently working schema is APPS? is that what you mean?? 

if that so, I have another question.

I already have an existing table called `testarie` in APPS schema. But when I tried to 
`var col1 = new Oracle.Collection("testarie");`, it seems it create a new table called `"testarie"`.
because I can do `select * from testarie;` => my old table with complete column and data
and I also can do `select * from "testarie";` => new table with `_id` column only and blank data
So I can't select data from the existing table which is `testarie`.

**Comment by metstrike** [comment]
> so the currently working schema is APPS? is that what you mean??

Yes, that is what I meant, the current schema is the schema you login to, so in your case it's APPS.

> if that so, I have another question. I already have an existing table called testarie in APPS schema.

Ok, the driver is case sensitive, so you should access your original table with all uppercase letter i.e.:

`var col1 = new Oracle.Collection("TESTARIE");
`

There are few things though you should be aware of. 
1. The names of columns are also case sensitive, so you should refer to columns in filters, or sort clause all in uppercase
2. This package is by default trying to automatically alter table to add or extend the columns according to the data that is being inserted to the table, it will also automatically try to create a oplog table and a trigger on TESTARIE to support the reactivity. If you want to prevent the package to modify your schema or object in your schema, you should set the option strict: true.
3. The meteor typically expects the "_id" in a collection, that column is given by MongoDB, if your table TESTARIE doesn't have "_id" column, you may try the option sqlAddId: true, and every find() will generate a sql with fale _id column populated by rownum.

So if you choose to use these settings your default oracle options would look like this:

```
Oracle.setDefaultOracleOptions(
    {connection:
        {user: "APPS", 
        password: "APPS", 
        connectString : "xxx.xxx.xxx.xxx:1532/SID"
        },
        strict: true,
        sqlAddId: true
});
```

**Comment by marczzio** [comment]
NICE! it worked! Thank you so much. I will waiting for the next version so I can access to other Schema such as INV etc. Thanks
