### ISSUE TITLE
Support for collection relationships?

### ISSUE THREAD

**Issue by monobrow666** [metstrike/meteor-oracle#17]
Hi, how can I use relationships between collections? For example, in the Todos example, how can I define a relationship between a todo and list such that selecting a list also selects its todos?

**Comment by metstrike** [comment]
So far this package provides no support for relationships or joins. There are other packages that implement reactive joins (for example method Meteor.publishComposite() [https://github.com/englue/meteor-publish-composite]) but they may need to be modified to work with Oracle.Collection

**Comment by monobrow666** [comment]
Ok, thanks. I found a decent solution using the models pattern suggested by David Weldon [http://dweldon.silvrback.com/models]. It's essentially the same thing as collection-helpers, but it doesn't extend Mongo.Collection, so it's database-independent.

I noticed that you have reactive joins in your roadmap. Have you started work on that yet?

**Comment by metstrike** [comment]
We didn't come up with an efficient design for reactive joins, I guess we should wait to see how it is addressed in Meteor/Apollo.

**Comment by monobrow666** [comment]
Ok, I'll watch Apollo. Thanks!
