### ISSUE TITLE
Oracle maximum name length reached.

### ISSUE THREAD

**Issue by relvar99** [metstrike/meteor-oracle#4]
All,

In certain cases, especially in nested documents, the package will create unique indexes with names that are greater than the allowed 32 length.  Of course, this is a more general issue, but when the package creates database objects on behalf of the user, it should be sure that it can before trying to do so I think.

Thanks,
Spencer

**Comment by metstrike** [comment]
Yes, the hard limit of 32 characters is a problem and currently the package lets Oracle to fail the command. Please note, the current implementation of nested documents in the package is experimental and we don't recommend to it at this moment. Without nested data structures the limit of 32 characters should be sufficient most of the time.
