### ISSUE TITLE
Errors while adding packages

### ISSUE THREAD

**Issue by ttahbaz** [metstrike/meteor-oracle#7]
I'm getting the following error when trying to run the todos-oracle sample:

> => Errors while adding packages:  
> While checking for metstrike:meteor-oracle@0.2.0:
> error: No compatible binary build found for this package. Contact the package author and ask them to publish it for yourplatform.

I'm pretty sure I have Oracle's instantclient installed correctly.  Any suggestions?

<img width="1399" alt="screen shot 2016-02-15 at 8 39 53 am" src="https://cloud.githubusercontent.com/assets/4433961/13053676/026a6582-d3c3-11e5-88e1-ac269090ecf9.png">

**Comment by metstrike** [comment]
The package is dependent on node-oracledb which contains binaries that have been compiled and published to the atmospherejs for **os.linux.x86_64** architecture only.

For **OSX** I would suggest to check out this repository, set environment variable to point meteor to it and then the binaries should be automatically recompiled for your local platform. Please try the following steps:

```
$ cd ~/workspace
$ git clone https://github.com/metstrike/meteor-oracle.git
$ export PACKAGE_DIRS="~/workspace"

$ cd ~/workspace/todos-oracle
$ meteor add metstrike:meteor-oracle
```
