### ISSUE TITLE
Oracle 12c 

### ISSUE THREAD

**Issue by zkvlt** [metstrike/meteor-oracle#8]
Will this work with 12c? Thanks for the great work @metstrike

**Comment by metstrike** [comment]
Yes, it works Oracle 12c as well. Although the package that has been published to atmospherejs has been pre-built for Oracle instant client 11.2 and os.linux.x86_64 architecture, you can check out this repository and have the binaries automatically recompiled for different version or architecture.

Please try the following steps:

$ cd ~/workspace
$ git clone https://github.com/metstrike/meteor-oracle.git
$ export PACKAGE_DIRS="~/workspace"

$ cd ~/workspace/todos-oracle
$ meteor add metstrike:meteor-oracle
