### ISSUE TITLE
Error connecting to existing Oracle DB

### ISSUE THREAD

**Issue by zkvlt** [metstrike/meteor-oracle#9]
Connection to Oracle was successful. But in your examples, you only mentioned how to create a new Oracle collection using:

`var coll = new Oracle.Collection("todos");`

But, I am trying to access an existing Oracle table. Tried this:

`var coll = Oracle.Collection("todos");`

but it throws this error:

> Error: use "new" to construct a Mongo.Collection
>     at Object.Mongo.Collection (packages/mongo/collection.js:29:1)
>     at Object.Oracle.Collection (packages/metstrike_meteor-oracle/lib/server/collection.js:19:1)
>     at server/lib/collections.js:27:14
>     at /usr/share/nginx/html/moe-oracle/bundle/programs/server/app/server/lib/collections.js:41:4
>     at /usr/share/nginx/html/moe-oracle/bundle/programs/server/boot.js:242:10
>     at Array.forEach (native)
>     at Function._.each._.forEach (/usr/share/nginx/html/moe-oracle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
>     at /usr/share/nginx/html/moe-oracle/bundle/programs/server/boot.js:137:5

Is it possible to connect to an existing Oracle table without first creating it in the Meteor app?

**Comment by metstrike** [comment]
You should still use "new" to create a new collection object, no matter if table exists or not.

**Comment by zkvlt** [comment]
Thanks @metstrike. Thats what I thought initially but just wanted confirmation from you I guess because of the 'production' nature of the database.
